### ISSUE TITLE
the api is old

### ISSUE THREAD

**Issue by pangff** [rejasupotaro/MaterialDesignSample#1]

**Comment by pangff** [comment]
such as setViewName has changed to setTransitionName. such as palette.getDarkVibrantColor has added an defaultColor parameter. and compiled with 5.0.1 it got an error : Unable to start activity ComponentInfo{rejasupotaro.sample/rejasupotaro.sample.controllers.ArticleListActivity}: java.lang.RuntimeException: Unknown scene name: moveImage
            at android.app.ActivityTh

**Comment by rejasupotaro** [comment]
Sorry, last update is a year ago, so I updated the architecture of this app. Please check it.
